stageis:
  - test
  - build

build-job:
  stage: build
  image: python:3-alpine
  script:
  - echo "Building..."
  artifacts:
    paths:
      - ./
  tags:
    - shell
  when: always

test-job:
  stage: test
  script:
    - echo "Testing..."
